sudo: required
services:
  - docker

before_install:
  - docker build -t discoveranirban/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true discoveranirban/docker-react npm run test -- --coverage